CREATE TABLE address
(
    id     bigint                 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    street character varying(255) NOT NULL,
    CONSTRAINT address_pkey PRIMARY KEY (id)
);

CREATE TABLE user_
(
    id         bigint                              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    age        integer,
    login      character varying(255)              NOT NULL,
    password   character varying(255)              NOT NULL,
    name       character varying(255)              NOT NULL,
    role       character varying(255) DEFAULT USER NOT NULL,
    address_id bigint,
    CONSTRAINT user__pkey PRIMARY KEY (id),
    CONSTRAINT uk_595avk25fuwifq27av9e3ixqn UNIQUE (login),
    CONSTRAINT fkt99kx4fa0okdr2keid6re132i FOREIGN KEY (address_id) REFERENCES address (id)
);

CREATE TABLE phone
(
    id      bigint                 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    number  character varying(255) NOT NULL,
    user_id bigint                 NOT NULL,
    CONSTRAINT phone_pkey PRIMARY KEY (id),
    CONSTRAINT fk4snqtiiyxfaoxodikxcmwytwn FOREIGN KEY (user_id) REFERENCES user_ (id)
);
