public interface Versions {
    String assertj = "3.17.2";
    String flyway = "7.3.2";
    String freemaker = "2.3.30";
    String gson = "2.8.6";
    String guava = "29.0-jre";
    String hikariCP = "3.4.5";
    String javassist = "3.24.0-GA";
    String javax_servlet = "4.0.1";
    String javax_annotation_api = "1.3.2";
    String javax_validation_api = "2.0.1.Final";
    String jetty = "11.0.0";
    String jmock = "2.12.0";
    String json_api = "1.1.4";
    String junit = "5.7.1";
    String reflections = "0.9.11";
    String hibernate = "5.4.27.Final";
    String hibernate_validator = "6.2.0.Final";
    String logback = "1.3.0-alpha5";
    String mockito = "3.5.13";
    String postgresql = "42.2.18";
    String springboot = "2.3.4.RELEASE";
    String spring_framework = "5.3.3";
    String testcontainers = "1.15.1";
    String thymeleaf = "3.0.12.RELEASE";

    String grpcVersion = "1.36.0";
    String protobufVersion = "3.15.2";
    String protocVersion = protobufVersion;
}