<ul id="menu">
    <li><a href="/">/</a></li>
    <li><a href="/user">Пользователь</a></li>
    <li><a href="/admin">Администратор</a></li>
    <li><a href="/admin/user/create">Добавить пользователя</a></li>
    <li class="menu_right"><a href="/login">Вход</a></li>
    <li class="menu_right">
        <form action="/logout" method="post">
            <input type="submit" value="Выход" >
        </form>
    </li>
</ul>