server:
    port: 8080

spring:
    application:
        name: web-message-system-app
    datasource:
        url: jdbc:postgresql://localhost:5432/demoDB
        username: usr
        password: pwd
    flyway:
        locations: "classpath:db/migration"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        show-sql: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                generate_statistics: false
                enable_lazy_load_no_trans: false
                format_sql: true

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.hibernate: INFO
        org.hibernate.SQL: DEBUG
